name: Building with GitHub Actions and Deploying into EC2 (Tomcat)

on:
  push:
    branches:
      - main

jobs:
  build_and_upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository into GitHub Runner
        uses: actions/checkout@v3

      - name: Install and setup Maven and Java within GitHub Runner
        uses: actions/setup-java@v3
        with: 
          distribution: "adopt"
          java-version: "11"
      
      - name: Build artifact with Maven
        run: mvn clean package
      
      - name: Upload Maven artifact into GitHub Packages
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: target/*.war

  deploy_to_qa:
    needs: build_and_upload_artifact
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp
      
      - name: Deploy to QA Environment
        run: |
          scp -i ${{ secrets.SECONDINSTANCEKEYPAIR }} -o StrictHostKeyChecking=no ./webapp/*.war ${{ secrets.INSTANCE_LOGIN }}:/opt/tomcat/webapps/

  deploy_to_prod:
    needs: deploy_to_qa
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: webapp
      
      - name: Deploy to Production Environment
        run: |
          scp -i ${{ secrets.SECONDINSTANCEKEYPAIRY }} -o StrictHostKeyChecking=no ./webapp/*.war ${{ secrets.INSTANCE_LOGIN }}:/opt/tomcat/webapps/
