name: Building with GitHub actions and deploying into EC2 (Tomcat)

on:
    push:
        branches:
            - main

jobs:
    build_and_upload_artifact:
        runs-on: ubuntu-latest
        steps:
            - name: clone repository into GitHub Runner
              uses: actions/checkout@v3

            - name: install and setup maven and Java within GitHub Runner
              uses: actions/setup-java@v3
              with: 
                distribution: "adopt"
                java-version: "11"
            
            - name: build artifact with Maven
              run: mvn clean package
            
            - name: upload maven artifact into GitHub Packages
              uses: actions/upload-artifact@v3
              with:
                name: webapp
                path: target/*.war
        
    deploy_artifact:
        runs-on: ubuntu-latest
        needs: build_and_upload_artifact
        steps:
            - name: clone repository into new runner
              uses: actions/checkout@v3

            - name: set up maven within new runner
              uses: actions/setup-java@v3
              with:
                distribution: "adopt"
                java-version: "11"

            - name: build artifact with maven
              run: mvn package
            

            - name: run sonarqube scan against code
              run: mvn sonar:sonar -Dsonar.url=http://3.84.14.143:9000
              

            - name: provide Github Runner with the key pair to our Tomcat Instance
              run: echo "${{secrets.SECONDINSTANCEKEYPAIR}}" > ~/secondinstancekey.pem
              
            - name: securely move our artifact into our tomcat server
              run: scp -i~/secondinstancekeypair.pem -o StrictHostKeyChecking=no target/*.war ${{secrets.INSTANCE_LOGIN}}:/opt/tomcat9/webapps
